spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ViitorQuadros/microservice-java.git
          search-paths:
          - Configs/{application}
server:
  port: 8888
