spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ViitorQuadros/microservice-java.git
          search-paths:
          - Configs/{application}
management:
  endpoints:
    web:
     exposure:
       include:
       - '*'
server:
  port: 8888
